# Generated by Django 4.2.13 on 2024-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_topic_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_required',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
